name: Deploy to Artifactory staging

on:
  # Only called by other workflows
  workflow_call:
    secrets:
      STAGING_ARTIFACTORY_USERNAME:
        required: true
      STAGING_ARTIFACTORY_PASSWORD:
        required: true

permissions:
  contents: write # Allow writing to the repository (e.g., commits, pushes)

jobs:
  deploy-emodpy-staging:
    name: Deploy to staging
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'Bump version: ')"
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install .[packaging] --index-url=https://packages.idmod.org/api/pypi/pypi-production/simple
      - name: Build and publish
        env:
          TWINE_REPOSITORY_URL: https://packages.idmod.org/api/pypi/idm-pypi-staging/
          TWINE_USERNAME: ${{ secrets.STAGING_ARTIFACTORY_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.STAGING_ARTIFACTORY_PASSWORD }}
        run: |
          python -m build --wheel
          twine upload dist/*
